curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"utils","version":"1.0.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"utils","version":"1.1.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"utils","version":"1.2.0"}}' --compressed

curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"dsl","version":"1.0.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"dsl","version":"1.1.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"dsl","version":"1.2.0"}}' --compressed

curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"nav","version":"1.0.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"nav","version":"1.1.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"nav","version":"1.2.0"}}' --compressed

curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"home","version":"1.0.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"home","version":"1.1.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"home","version":"1.2.0"}}' --compressed

curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"search","version":"1.0.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"search","version":"1.1.0"}}' --compressed
curl 'http://localhost:3000/api/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"mutation($application: String!, $version:String!) {\n  addVersion(application: $application, version: $version) {\n    latest\n  }\n}","variables":{"application":"search","version":"1.2.0"}}' --compressed
